2021-01-05 22:43:38,087 ERROR: Exception on /search [GET] [in c:\users\phuhi\onedrive - fpt software\learning\flask\microblog\venv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "c:\users\phuhi\onedrive - fpt software\learning\flask\microblog\venv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\phuhi\onedrive - fpt software\learning\flask\microblog\venv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\phuhi\onedrive - fpt software\learning\flask\microblog\venv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\phuhi\onedrive - fpt software\learning\flask\microblog\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\phuhi\onedrive - fpt software\learning\flask\microblog\venv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\phuhi\onedrive - fpt software\learning\flask\microblog\venv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\phuhi\onedrive - fpt software\learning\flask\microblog\venv\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\phuhi\OneDrive - FPT Software\Learning\Flask\microblog\app\main\routes.py", line 154, in search
    posts,total = Post.search(g.search_form.q.data, page, current_app.config['POSTS_PER_PAGE'])
  File "C:\Users\phuhi\OneDrive - FPT Software\Learning\Flask\microblog\app\models.py", line 14, in search
    ids, total = query_index(cls.__tablename__, expression, page,per_page)
  File "C:\Users\phuhi\OneDrive - FPT Software\Learning\Flask\microblog\app\search.py", line 30, in query_index
    ids = [int (hit['_id']) for hit in search['hits']['hits']]
  File "C:\Users\phuhi\OneDrive - FPT Software\Learning\Flask\microblog\app\search.py", line 30, in <listcomp>
    ids = [int (hit['_id']) for hit in search['hits']['hits']]
ValueError: invalid literal for int() with base 10: '<Post one\r\n>'
2021-01-05 22:45:24,410 INFO: Microblog startup [in C:\Users\phuhi\OneDrive - FPT Software\Learning\Flask\microblog\app\__init__.py:77]
2021-01-05 22:45:26,781 ERROR: Exception on /search [GET] [in c:\users\phuhi\onedrive - fpt software\learning\flask\microblog\venv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "c:\users\phuhi\onedrive - fpt software\learning\flask\microblog\venv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\phuhi\onedrive - fpt software\learning\flask\microblog\venv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\phuhi\onedrive - fpt software\learning\flask\microblog\venv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\phuhi\onedrive - fpt software\learning\flask\microblog\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\phuhi\onedrive - fpt software\learning\flask\microblog\venv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\phuhi\onedrive - fpt software\learning\flask\microblog\venv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\phuhi\onedrive - fpt software\learning\flask\microblog\venv\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\phuhi\OneDrive - FPT Software\Learning\Flask\microblog\app\main\routes.py", line 154, in search
    posts,total = Post.search(g.search_form.q.data, page, current_app.config['POSTS_PER_PAGE'])
  File "C:\Users\phuhi\OneDrive - FPT Software\Learning\Flask\microblog\app\models.py", line 14, in search
    ids, total = query_index(cls.__tablename__, expression, page,per_page)
  File "C:\Users\phuhi\OneDrive - FPT Software\Learning\Flask\microblog\app\search.py", line 30, in query_index
    ids = [int (hit['_id']) for hit in search['hits']['hits']]
  File "C:\Users\phuhi\OneDrive - FPT Software\Learning\Flask\microblog\app\search.py", line 30, in <listcomp>
    ids = [int (hit['_id']) for hit in search['hits']['hits']]
ValueError: invalid literal for int() with base 10: '<Post one\r\n>'
2021-01-05 22:45:40,773 ERROR: Exception on /search [GET] [in c:\users\phuhi\onedrive - fpt software\learning\flask\microblog\venv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "c:\users\phuhi\onedrive - fpt software\learning\flask\microblog\venv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\phuhi\onedrive - fpt software\learning\flask\microblog\venv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\phuhi\onedrive - fpt software\learning\flask\microblog\venv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\phuhi\onedrive - fpt software\learning\flask\microblog\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\phuhi\onedrive - fpt software\learning\flask\microblog\venv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\phuhi\onedrive - fpt software\learning\flask\microblog\venv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\phuhi\onedrive - fpt software\learning\flask\microblog\venv\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\phuhi\OneDrive - FPT Software\Learning\Flask\microblog\app\main\routes.py", line 154, in search
    posts,total = Post.search(g.search_form.q.data, page, current_app.config['POSTS_PER_PAGE'])
  File "C:\Users\phuhi\OneDrive - FPT Software\Learning\Flask\microblog\app\models.py", line 14, in search
    ids, total = query_index(cls.__tablename__, expression, page,per_page)
  File "C:\Users\phuhi\OneDrive - FPT Software\Learning\Flask\microblog\app\search.py", line 30, in query_index
    ids = [int (hit['_id']) for hit in search['hits']['hits']]
  File "C:\Users\phuhi\OneDrive - FPT Software\Learning\Flask\microblog\app\search.py", line 30, in <listcomp>
    ids = [int (hit['_id']) for hit in search['hits']['hits']]
ValueError: invalid literal for int() with base 10: '<Post one\r\n>'
2021-01-05 22:48:53,905 INFO: Microblog startup [in C:\Users\phuhi\OneDrive - FPT Software\Learning\Flask\microblog\app\__init__.py:77]
